### ISSUE TITLE
There is null display in current play area when currentMessage is not been set

### ISSUE THREAD

**Issue by maxwang** [rocco/mediaelement-playlist-plugin#2]
Hi,
Please check below image when  currentMessage is not been:
![playlist_null](https://user-images.githubusercontent.com/716782/39902105-a0982328-550f-11e8-8274-8b575e8ba822.PNG)

**Comment by rocco** [comment]
could you provide a complete code example @maxwang?

**Comment by maxwang** [comment]
Hi Rocco,
Please check below code, almost same as demo code:

$('audio').mediaelementplayer({
        features: ['prevtrack', 'playpause', 'nexttrack', 'current', 'progress', 'duration', 'volume', 'playlist', 'shuffle'],
        success: function (player, node) {

            // Optional
            $(player).closest('.mejs__container').attr('lang', mejs.i18n.language());

            $('html').attr('lang', mejs.i18n.language());

            // More code
        }
    });

But below works:

$('audio').mediaelementplayer({
        features: ['prevtrack', 'playpause', 'nexttrack', 'current', 'progress', 'duration', 'volume', 'playlist', 'shuffle'],
        currentMessage: "",
        success: function (player, node) {

            // Optional
            $(player).closest('.mejs__container').attr('lang', mejs.i18n.language());

            $('html').attr('lang', mejs.i18n.language());

            // More code
        }
    });

I found in playlist.js
line 104, change
${player.options.currentMessage}
to
${player.options.currentMessage || ''} will fix this issue

**Comment by rocco** [comment]
looks good. do you not want to open a PR for it (you can edit the file online and open the PR from there)?

**Comment by maxwang** [comment]
Hi Rocco,
I already send a pull request at 11st of May from my branch. Do you want me open a pull request from here?

Thanks.

**Comment by rocco** [comment]
The pull request does not appear here...
https://github.com/rocco/mediaelement-playlist-plugin/pulls?utf8=%E2%9C%93&q=is%3Apr

Anyways I'll update the file - thanks for the fix!

**Comment by rocco** [comment]
This cannot be fixed here - there is no playlist.js file in this repo.
